### ISSUE TITLE
Rename `setters` module to `sett-standards`

### ISSUE THREAD

**Issue by ghost** [setheum/setheum#301]

**Comment by balqaasem** [comment]
Been renamed, but to `setters-manager` instead... it fits better to the purpose of the setheum_setters module (Setheum Setters). So, "Setters Manager". Right?!

Closes it on #314

**Comment by balqaasem** [comment]
Closed on https://github.com/Setheum-Labs/Setheum/pull/314/commits/27c3dabdd4ee0055f0c0f47e3a5e7f06cfeb3c89 and in the #314 PR
