### ISSUE TITLE
Al-Ethaar Protocol - Quadratic Funding

### ISSUE THREAD

**Issue by balqaasem** [setheum/setheum#724]
Create Al-Ethaar Protocol and let people donate to a cause all on-chain, Setheum's Quadratic Funding Project for Non-Profits. Al-Ethaar Protocol is different from SPF

**Comment by balqaasem** [comment]
This reference could be a good start https://github.com/OAK-Foundation/quadratic-funding-pallet/blob/main/pallets/open-grant/src/lib.rs

**Comment by balqaasem** [comment]
Let the public be able to donate in Ethaar, when a campaign is approved

**Comment by JBA-Khalifa** [comment]
Migrate SPF on-chain and transfer all funds to the NEW now OnChain `EthaarFundAccount`

**Comment by balqaasem** [comment]
Support `MultiCurrency`, such that projects could raise multiple curencies in differing amounts, or each currency has its own round and teams could chose which currency round they want to join by their `CurrencyId` choice of funding.
Any of the two will be good, but I think the latter is more efficient, more welcoming with more varieties, and more competutive as projects can only choose to join 1 pool/round. 
Lets see if `multiround/multipool` projects will be viable, because they can also provide a lot of opportunities like projects that raise a few `SETUSD` could raise a large sum of `SETR` and vice-versa with all Setheum Currencies.

We can decide on that insha'Allah

**Comment by balqaasem** [comment]
Ref for Initial Implementation: https://github.com/Setheum-Labs/Setheum/pull/735/commits/958762dd6476aff1cae7beab9941caa10b955926
